USE [master]
GO

/****** Object:  Database [vt1]    Script Date: 02/28/2009 14:14:58 ******/
CREATE DATABASE [vt1] ON  PRIMARY 
( NAME = N'vt1', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS2\MSSQL\DATA\vt1.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'vt1_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10.SQLEXPRESS2\MSSQL\DATA\vt1_1.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [vt1] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [vt1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [vt1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [vt1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [vt1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [vt1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [vt1] SET ARITHABORT OFF 
GO

ALTER DATABASE [vt1] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [vt1] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [vt1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [vt1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [vt1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [vt1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [vt1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [vt1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [vt1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [vt1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [vt1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [vt1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [vt1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [vt1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [vt1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [vt1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [vt1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [vt1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [vt1] SET  READ_WRITE 
GO

ALTER DATABASE [vt1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [vt1] SET  MULTI_USER 
GO

ALTER DATABASE [vt1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [vt1] SET DB_CHAINING OFF 
GO

