CREATE FUNCTION DBO.DURUM(@X TINYINT) RETURNS VARCHAR(30)
AS
BEGIN
DECLARE @SONUC VARCHAR(30)
SET @SONUC= CASE WHEN @X<25 THEN 'GENÇ'
WHEN @X>=25 AND @X<40 THEN 'ORTA YAÞ'
ELSE 'YAÞLI'
END
RETURN @SONUC
END


SELECT SICILNO,ADSOYAD,YAS,DBO.DURUM(YAS) AS DURUM,SEHIR
FROM CALISANLAR